# Generated by Django 3.2 on 2022-08-06 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('phone', models.CharField(max_length=20, verbose_name='phone number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=20, verbose_name='address')),
                ('city', models.CharField(max_length=20, verbose_name='city')),
                ('company', models.CharField(max_length=20, verbose_name='company')),
                ('postalZip', models.IntegerField(blank=True, null=True, verbose_name='postal zip code')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.customer', verbose_name='customer')),
            ],
            options={
                'verbose_name': 'Место работы',
                'db_table': 'work_place',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.IntegerField(blank=True, null=True, verbose_name='pin code')),
                ('acc_num', models.CharField(max_length=20, verbose_name='account number')),
                ('pan', models.CharField(max_length=20, verbose_name='permanent account number')),
                ('cvv', models.IntegerField(verbose_name='card verification number')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.customer', verbose_name='customer')),
            ],
            options={
                'verbose_name': 'Аккаунт',
                'verbose_name_plural': 'Аккаунты',
                'db_table': 'accounts',
            },
        ),
    ]
